### ISSUE TITLE
[installation] Minimal version of Node/npm ? Failures when installing

### ISSUE THREAD

**Issue by YannZeRookie** [brh55/botkit-discord#10]
Hi,
What is the minimal version required of NodeJS and npm? I am using the LTS 10.16.0 version of Node (npm 6.9.0) and I get tons of problems with ffmpeg when doing:
 `npm install git+ssh://git@github.com/brh55/botkit-discord.git`:

```
npm WARN deprecated ffmpeg-binaries@4.0.0: ffmpeg-binaries is no longer being maintained. use ffmpeg-static, or just install ffmpeg
npm WARN deprecated uws@99.0.0: New code is available at github.com/uNetworking/uWebSockets.js
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead

> lzma-native@3.0.8 install /var/www/lsd/bot/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

[lzma-native] Success: "/var/www/lsd/bot/node_modules/lzma-native/binding-v3.0.8-node-v64-linux-x64/lzma_native.node" is installed via remote

> erlpack@0.1.0 install /var/www/lsd/bot/node_modules/erlpack
> node-gyp rebuild

make: Entering directory '/var/www/lsd/bot/node_modules/erlpack/build'
  CC(target) Release/obj.target/zlib/vendor/zlib/adler32.o
  CC(target) Release/obj.target/zlib/vendor/zlib/compress.o
  CC(target) Release/obj.target/zlib/vendor/zlib/crc32.o
  CC(target) Release/obj.target/zlib/vendor/zlib/deflate.o
  CC(target) Release/obj.target/zlib/vendor/zlib/gzclose.o
  CC(target) Release/obj.target/zlib/vendor/zlib/gzlib.o
  CC(target) Release/obj.target/zlib/vendor/zlib/gzread.o
  CC(target) Release/obj.target/zlib/vendor/zlib/gzwrite.o
  CC(target) Release/obj.target/zlib/vendor/zlib/infback.o
  CC(target) Release/obj.target/zlib/vendor/zlib/inffast.o
  CC(target) Release/obj.target/zlib/vendor/zlib/inflate.o
  CC(target) Release/obj.target/zlib/vendor/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/vendor/zlib/trees.o
  CC(target) Release/obj.target/zlib/vendor/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/vendor/zlib/zutil.o
  AR(target) Release/obj.target/vendor/zlib.a
  COPY Release/zlib.a
  CXX(target) Release/obj.target/erlpack/js/erlpack.o
In file included from ../js/erlpack.cc:2:0:
../js/encoder.h: In member function 'int Encoder::pack(v8::Local<v8::Value>, int)':
../js/encoder.h:58:44: warning: 'int32_t v8::Value::Int32Value() const' is deprecated (declared at /home/deploy/.node-gyp/10.16.0/include/node/v8.h:2478): Use maybe version [-Wdeprecated-declarations]
             int number = value->Int32Value();
                                            ^
../js/encoder.h:67:68: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated (declared at /home/deploy/.node-gyp/10.16.0/include/node/v8.h:2477): Use maybe version [-Wdeprecated-declarations]
                 auto uNum = (unsigned long long)value->Uint32Value();
                                                                    ^
../js/encoder.h:72:49: warning: 'double v8::Value::NumberValue() const' is deprecated (declared at /home/deploy/.node-gyp/10.16.0/include/node/v8.h:2475): Use maybe version [-Wdeprecated-declarations]
             double decimal = value->NumberValue();
                                                 ^
  SOLINK_MODULE(target) Release/obj.target/erlpack.node
  COPY Release/erlpack.node
make: Leaving directory '/var/www/lsd/bot/node_modules/erlpack/build'

> ffmpeg-binaries@4.0.0 install /var/www/lsd/bot/node_modules/ffmpeg-binaries
> node install

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND johnvansickle.com johnvansickle.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN lsd-bot@0.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-binaries@4.0.0 install: `node install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-binaries@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2019-06-01T11_53_57_020Z-debug.log
```

**Comment by brh55** [comment]
You should only need "Node.js 6.0.0 or newer is required." per discord.js. But are you using any of the audio features?

**Comment by brh55** [comment]
Currently, I'm trying to remove the dependencies of opusscript and ffmpeg, then provide install instructions if you plan on using the audio feature.
From my current testing, it works fine without those dependencies installed, but not if you install them independently and try to use the API.

**Comment by YannZeRookie** [comment]
OK, I'll try with this version of Node. I don't need the audio features - how do I turn this dependency off?
Looking forward to your instructions,
Thanks in advance!

**Comment by brh55** [comment]
@YannZeRookie try the latest v0.1.1, I've removed the hard dependencies of node-opus, opusscript, and ffmpeg. Now the framework should work just fine, I'll add additional instructions if someone wants to use the audio features.

**Comment by YannZeRookie** [comment]
Hi @brh55 , I confirm that the install now runs smoothly, thanks!
